# Generated by Django 2.0.13 on 2019-05-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. Money', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex. B1.2', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(help_text='Ex. Travel', max_length=60)),
                ('spanish_word', models.CharField(help_text='Ex. Viajar', max_length=60)),
                ('spanish_pronunciation', models.CharField(blank=True, help_text='Ex. trável (puedes usar las tildes para acentuar donde se hace el énfasis en la pronunciación)', max_length=60, null=True)),
                ('phonetics', models.CharField(blank=True, help_text='Ex. /ˈtræv(ə)l/. Get it on: https://www.macmillandictionary.com/', max_length=60, null=True)),
                ('notes', models.TextField(blank=True, help_text='Ex. Suele usarse como verbo, rara como sustantivo o adjetivo', max_length=4000, null=True)),
                ('category', models.ManyToManyField(to='dictionary.Category')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.Level')),
            ],
        ),
    ]
