# Generated by Django 2.0.13 on 2019-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_important',
            field=models.BooleanField(default=False, help_text='This word has extra score for exams in the same level'),
        ),
    ]
