# Generated by Django 2.0.13 on 2019-05-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_word_is_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='level',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dictionary.Level'),
        ),
    ]
