# Generated by Django 2.0.13 on 2019-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_auto_20190517_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetics',
            field=models.CharField(blank=True, help_text='Ex. /ˈtræv(ə)l/. Get it on: https://www.wordreference.com/', max_length=60, null=True),
        ),
    ]
