# Generated by Django 2.0.13 on 2019-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_auto_20190518_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='phonetics',
            field=models.CharField(blank=True, help_text='Ex. /ˈtræv(ə)l/. Get it on: https://dictionary.cambridge.org/es/', max_length=60, null=True),
        ),
    ]
