# Generated by Django 2.0.13 on 2019-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20190525_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spanish_word',
            field=models.CharField(help_text='Ex. Viajar', max_length=100),
        ),
    ]
